import { OffkaiEvent } from "@/types/event";

const base = new Date();
const d = (offsetDays: number, hour = 19) => {
  const t = new Date(base);
  t.setDate(t.getDate() + offsetDays);
  t.setHours(hour, 0, 0, 0);
  return t.toISOString();
};

// モックデータ：APIキー取得後は実データに自動切替
// URLはモックなので各サービスの東京イベント検索ページへ
const CONNPASS_TOKYO = "https://connpass.com/search/event/?prefectures=tokyo&order=2";
const PEATIX_TOKYO = "https://peatix.com/search?q=&country=JP&location=Tokyo%2C+Japan";
const MEETUP_TOKYO = "https://www.meetup.com/find/?location=jp--Tokyo&source=EVENTS";
const KOKUCHIZU_TOKYO = "https://kokucheese.com/search/?pref=tokyo";

export const MOCK_EVENTS: OffkaiEvent[] = [
  {
    id: "connpass-1001",
    source: "connpass",
    title: "Tokyo Web勉強会 #42 〜React最新動向を語る夜〜",
    description: "ReactとNext.jsの最新アップデートについて気軽に話しましょう！",
    startAt: d(1),
    endAt: d(1, 21),
    location: "渋谷区文化総合センター大和田 4F",
    url: CONNPASS_TOKYO,
    isFree: true,
    capacity: 30,
    attendeeCount: 18,
    tags: ["React", "Next.js", "TypeScript"],
    organizer: "Tokyo Web Dev",
  },
  {
    id: "connpass-1002",
    source: "connpass",
    title: "Python×AI ハンズオン！生成AIアプリ入門",
    description: "OpenAI APIを使ったアプリ開発を手を動かして学びます。",
    startAt: d(2),
    endAt: d(2, 21),
    location: "新宿某所（申込後に案内）",
    url: CONNPASS_TOKYO,
    isFree: false,
    price: 1000,
    capacity: 20,
    attendeeCount: 14,
    tags: ["Python", "AI", "OpenAI"],
    organizer: "Python Tokyo",
  },
  {
    id: "connpass-1003",
    source: "connpass",
    title: "インフラ・SRE もくもく会 @秋葉原",
    description: "各自作業しながらインフラ・SRE系の話をゆるくする会です。",
    startAt: d(3, 18),
    endAt: d(3, 21),
    location: "秋葉原UDX",
    url: CONNPASS_TOKYO,
    isFree: true,
    capacity: 15,
    attendeeCount: 9,
    tags: ["SRE", "Kubernetes", "AWS"],
    organizer: "Tokyo SRE",
  },
  {
    id: "peatix-2001",
    source: "peatix",
    title: "写真好き集まれ！カメラ女子・男子オフ会 in 代官山",
    description: "カメラ好きが集まって代官山を散歩しながら撮影するオフ会です。",
    startAt: d(1, 14),
    endAt: d(1, 17),
    location: "代官山 蔦屋書店前",
    url: PEATIX_TOKYO,
    isFree: true,
    attendeeCount: 22,
    tags: ["カメラ", "写真", "撮影"],
    organizer: "Tokyo Photo Walk",
  },
  {
    id: "peatix-2002",
    source: "peatix",
    title: "ボードゲームナイト！初心者歓迎 @池袋",
    description: "みんなでボードゲームを楽しむ夜。初心者大歓迎です！",
    startAt: d(4, 18),
    endAt: d(4, 22),
    location: "池袋ゲームスペース",
    url: PEATIX_TOKYO,
    isFree: false,
    price: 500,
    capacity: 16,
    attendeeCount: 10,
    tags: ["ボードゲーム", "初心者歓迎"],
    organizer: "池袋ボドゲ部",
  },
  {
    id: "meetup-3001",
    source: "meetup",
    title: "Tokyo International Language Exchange",
    description: "日本語・英語・その他言語を交換しながら交流するイベント。",
    startAt: d(2, 18),
    endAt: d(2, 21),
    location: "六本木ヒルズ森タワー",
    url: MEETUP_TOKYO,
    isFree: true,
    attendeeCount: 45,
    tags: ["語学", "国際交流", "英語"],
    organizer: "Tokyo Language Exchange",
  },
  {
    id: "meetup-3002",
    source: "meetup",
    title: "Startup Founders Networking Tokyo",
    description: "スタートアップ創業者・起業家のネットワーキングイベント。",
    startAt: d(5, 19),
    endAt: d(5, 22),
    location: "渋谷スクランブルスクエア",
    url: MEETUP_TOKYO,
    isFree: false,
    price: 2000,
    capacity: 50,
    attendeeCount: 38,
    tags: ["スタートアップ", "起業", "ネットワーキング"],
    organizer: "Tokyo Startup Hub",
  },
  {
    id: "kokuchizu-4001",
    source: "kokuchizu",
    title: "ランニング仲間募集！皇居ランオフ会",
    description: "皇居周辺を一緒に走りましょう。ペースは問いません！",
    startAt: d(0, 7),
    endAt: d(0, 9),
    location: "皇居 桔梗門前集合",
    url: KOKUCHIZU_TOKYO,
    isFree: true,
    attendeeCount: 12,
    tags: ["ランニング", "運動", "健康"],
    organizer: "皇居ランナーズ",
  },
  {
    id: "kokuchizu-4002",
    source: "kokuchizu",
    title: "読書会：SF小説を語ろう！#15",
    description: "今月のテーマはケン・リュウ作品。未読でも歓迎です。",
    startAt: d(6, 19),
    endAt: d(6, 21),
    location: "神保町某カフェ",
    url: KOKUCHIZU_TOKYO,
    isFree: true,
    capacity: 12,
    attendeeCount: 7,
    tags: ["読書", "SF", "文学"],
    organizer: "東京SF読書会",
  },
  {
    id: "connpass-1004",
    source: "connpass",
    title: "Flutter×Dart 勉強会 LT大会",
    description: "Flutter開発者によるLT5分×6本。懇親会もあります！",
    startAt: d(3, 19),
    endAt: d(3, 22),
    location: "品川区某所",
    url: CONNPASS_TOKYO,
    isFree: true,
    capacity: 40,
    attendeeCount: 31,
    tags: ["Flutter", "Dart", "モバイル"],
    organizer: "Flutter Tokyo",
  },
];
